### ISSUE TITLE
API to persist file mapped font data

### ISSUE THREAD

**Issue by tronical** [RazrFalcon/fontdb#18]
Hi,

I'm filing this issue as a API feature request and question. If concluded to be reasonable, I'd be more than happy to do submit an implementation, but I'm unclear about the best API for the use-case:

I'm using fontdb with the memmap feature enabled, on a file system on macOS, Linux and Windows. Initially loading/scanning the system fonts works great with `load_system_fonts`. Later, when I decide to pick a particular font and fontdb returns the Face ID, the `with_face_data` API allows accessing the data temporarily.

When rendering text then, I'm using ttf_parser and rustybuzz (indirectly via femtovg) and that works great. But whenever rendering text, there is a chance of encountering uncached glyphs or (more likely) access to the opentype tables, etc. is required for use with rustybuzz. With the current fontdb API that means that either every time a new temporary file mapping needs to be created/destroyed (`with_face_data`) or the entire font data needs to be duplicated in memory (copied into a `Vec<u8>`).

I'd like to figure out what the right API would be for fontdb to offer a way to make fontdb persist a file mapping for a given face id, in a way that for example fontdb could return for example an `Arc<dyn AsRef<[u8]>>` (or basically an `Arc` with the traits that `memmap2::Mmap` implements).

I thought of a function like `fn shared_face_source(&mut self, id: ID) -> Option<(Arc<dyn AsRef<[u8]>>, u32>)`, but I think implementation wise that wouldn't fit well with the existing `Vec<FaceInfo>` or more specifically the public `Source` enum. While that could in theory hold something like a `SharedBinary(Box<dyn AsRef<[u8]>>)` variant, it doesn't work in practice because `Source` also implements `Clone`.

So I'm curious: Is this a feature that you'd be willing to generally accept?

If yes, can you think of a way to implement this without breaking API compatibility?
If API compatibility is okay to break, what API would be acceptable?

Any input would be greatly appreciated - and as said: I'd be happy to get my hands dirty on an implementation.

**Comment by RazrFalcon** [comment]
I'm not sure I've understood the issue. 

You should not load font files into memory. Some fonts, like Apple Emoji, are like 150MB big. You will run out of memory fast. The reason the ability to load fonts into memory exists is for rare cases when you do not have an actual font file (WASM or compressed fonts or something like this).

And we cannot have a persistent mmaping, afaik, because it's unsafe. You can mmap a file. Delete it. Try access it and the app will crash.

So the only solution is to mmap a file on each access. And for something as heavy as shaping or glyphs outlining, the overhead should be neglectable.

You your use case I think we can add a function that will loaded the file into memory, basically swap the `Source`. Like `fn load_into_memory(&mut self, id: ID)`. So the next time you will need to access this font via `with_face_data` (for shaping presumably) it would be faster. But again, you will start "leaking" memory eventually. So it would be great to have a function to unload a font. We already have `remove_face`, but I would prefer a function that simply deallocates a font.
Maybe we can replace `File(PathBuf)` with `File(PathBuf, Option<Vec<u8>>)` or something like this.

Breaking changes are fine. But I'm not sure how can we improve this.

**Comment by tronical** [comment]
> You should not load font files into memory.

I agree :)

> And we cannot have a persistent mmaping, afaik, because it's unsafe. You can mmap a file. Delete it. Try access it and the app will crash.

I agree that there are ways to make this unsafe. For some applications that's unacceptable, for some applications it might be an acceptable risk (something I would choose to opt-in for fonts - I'm not concerned about the case of somebody truncating ttf files in the file system).

So I'm not looking for `load_in_memory` but an opt-in API to allow me to accept the risk.

> So the only solution is to mmap a file on each access. And for something as heavy as shaping or glyphs outlining, the overhead should be neglectable.

Especially for large fonts that's an allocation of a large amount of virtual address space - repeatedly when rendering text.

> Breaking changes are fine.

Here's an idea I just prototyped that maintains compatibility and permits an opt-in:

```rust
pub trait SharedFontData: AsRef<[u8]> + std::fmt::Debug {}

#[cfg(feature = "memmap")]
impl SharedFontData for memmap2::Mmap {}

impl SharedFontData for Vec<u8> {}

/// A font source.
///
/// Either a raw binary data or a file path.
///
/// Stores the whole font and not just a single face.
#[derive(Clone, Debug)]
pub enum Source {
    /// A font's raw data. Owned by the database.
    Binary(Vec<u8>),

    /// A font's path.
    #[cfg(feature = "fs")]
    File(PathBuf),

    /// A font's raw data shared between the database and the application.
    /// If the data originates from the file system, then it's a shared mapping.
    SharedBinary(Option<PathBuf>, Arc<dyn SharedFontData>),
}
```

and then 

```rust
/// Makes the font data that backs the specified face id shared so that the application can
/// hold a reference to it.
///
/// If the face originates from a file from disk, then the file is mapped from disk. This is unsafe as
/// another process may make changes to the file on disk, which may become visible
/// in this process' mapping and possibly cause crashes.
///
/// If the underlying font provides multiple faces, then all faces are updated to participate in
/// the data sharing. If the face was previously marked for data sharing, then this function will
/// return a clone of the existing reference.
pub unsafe fn make_shared_face_data(
        &mut self,
        id: ID,
    ) -> Option<(Arc<dyn SharedFontData>, u32)>;

/// Transfers ownership of shared font data back to the font database. This is the reverse operation
/// of [`Self::make_shared_face_data`]. If the font data belonging to the specified face is mapped
/// from a file on disk, then that mapping is closed and the data becomes private to the process again.
pub unsafe fn make_face_data_unshared(&mut self, id: ID);
```

I can submit this with the impl as PR if this looks like an okay direction.

**Comment by RazrFalcon** [comment]
Sorry, but I cannot accept this. This is too unsafe and we cannot hide it behind a safe interface. It violates Rust rules. A file must not be permanently open via mmap. You have to either fork this crate or cache fonts on you side.
And no, we cannot hide it behind a feature flag.

Also, I'm not sure your code will work in the first place. `memmap2::Mmap` depends on `std::fs::File`, which will violate borrowing rules, afaik. So you cannot store `memmap2::Mmap` in the first place.

I understand performance implications, but this is not a solution. On the other hand, opening a file is like 0.01% of text shaping. It's hard to see when it would be a bottleneck.

**Comment by tronical** [comment]
I've uploaded my prototype to GH at https://github.com/sixtyfpsui/fontdb/tree/simon/shared-data . But I'll respect your choice of course. If you agree then I'll happily create a PR and polish it. If you still disagree about supporting such an API as unsafely marked then that's okay, too.

In any case I hugely admire all the software that you have written, for its stability, it's clean APIs and awesome functionality :)

**Comment by RazrFalcon** [comment]
Hmm... as long as those functions are marked as `unsafe` - I'm fine. Just add a `# Safety` section, like [this one](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#safety), to them. Also update the safety section in the library docs, at the top. Just mention that there are exceptions to temporary mapping now.

The real problem now is that I honestly do not understand how your code works. What this code does: `Arc::new(data) as Arc<dyn AsRef<[u8]>>`? Can you explain it to me? You're storing a trait object to original data somehow? I didn't know that this is even possible. I'm surprised that this doesn't trigger lifetime issues.

>Is there something that I perhaps overlooked in the memmap2 crate?

Strange, I thought `Mmap` cannot outlive `File`, because `File` will close a descriptor in the destructor. Will double check later.

**Comment by tronical** [comment]
> Hmm... as long as those functions are marked as unsafe - I'm fine. Just add a # Safety section, like this one, to them. Also update the safety section in the library docs, at the top. Just mention that there are exceptions to temporary mapping now.

Sounds good!

> What this code does: Arc::new(data) as Arc<dyn AsRef<[u8]>>? Can you explain it to me? You're storing a trait object to original data somehow? I didn't know that this is even possible. I'm surprised that this doesn't trigger lifetime issues.

Sure :). You're right, this looks like the trait object is stored in the Arc. I think officially this is https://github.com/rust-lang/rfcs/blob/master/text/0982-dst-coercion.md . I think in practice this cast creates a "fat" pointer that firstly refers to the original data (for example the synthetic struct of Arc's refcount and the memmap::Map2 fd, or a Vec<u8>) and secondly to the vtable of the `dyn AsRef<[u8]>` implementation that fits the contained type. So the Arc implementation has a pointer to the data, which is all it needs to maintain the reference count. And the "vtable" allows the compiler to generate code to indirectly call `as_ref()`, where the implementation knows what's behind the data pointer as well (that's passed along).

An alternative API would be to not erase the type but have something like `Arc<memmap2::Map>`, but I think exposing memmapi in fontdb's public API is not desirable.

**Comment by RazrFalcon** [comment]
I see.

Yes, `&[u8]` if preferable.
