### ISSUE TITLE
Variable fonts get mismatched

### ISSUE THREAD

**Issue by Jasper-Bekkers** [RazrFalcon/fontdb#30]
This may be do to my own misunderstanding of fonts / this particular font, but preliminary investigation seems to suggest that fontdb ignores variable fonts (or at least, only takes a look at one variation).

https://fonts.google.com/specimen/Raleway specifically `Raleway-VariableFont_wght.ttf`

It looks like this only gets detected as "Raleway Thin" whereas ExtraLight, Light etc seem to be missing completely, causing the `query` functionality to skip over all of those.

**Comment by RazrFalcon** [comment]
This is the expected behaviour. The font has family name _Raleway Thin_, which is what `fontdb` is using. I guess this is just the default/fallback weight for this font.

I have no idea how variable fonts are supposed to be matched, but `fontdb` and `ttf-parser` do support them.

It seems like macOS does detect those variations. So we should try as well. Probably using the `fvar` table.

The problem with variable fonts is that they are poorly documented, at least to my knowledge. So figuring out how something suppose to work can be done only by trial and error. And I guess we could try matching macOS behaviour for now.

**Comment by Jasper-Bekkers** [comment]
> This is the expected behaviour. The font has family name Raleway Thin, which is what fontdb is using. I guess this is just the default/fallback weight for this font.

Makes sense, it's a bit confusing but I suppose you're right. The windows font dialog shows the same in the title of the window, and then it allows you to next/prev through all variations that do have appropriate names.

> It seems like macOS does detect those variations. So we should try as well. Probably using the fvar table.

It looks like windows does too.

**Comment by RazrFalcon** [comment]
I guess it sort of documented here: https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord

**Comment by RazrFalcon** [comment]
Fixed. You can match a font by passing just _Raleway_ now.
