### ISSUE TITLE
CSS queries by full name rather than family name

### ISSUE THREAD

**Issue by CryZe** [RazrFalcon/fontdb#7]
I'm currently looking to somewhat replicating the font lookup a browser does, and I stumbled upon this crate. However it seems to only be able to match against the family name rather than the full name. Is this something that you would consider adding, or that I could do a Pull Request for?

**Comment by RazrFalcon** [comment]
What do you mean by _full name_? A font can have a family name, subfamily name, typographic family name and typographic subfamily name. There are also special name generation algorithms like [this](https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp) one.

So the problem is not to change the current logic, but to understand what result we actually need.

**Comment by CryZe** [comment]
I believe I've seen it be referred to that in Firefox's source code? I'm not even sure anymore, I'm so confused at this point. Basically browsers can (sometimes?) match on "family name + typographic subfamily" or alternatively "family name + font variation instance" (Firefox doesn't support the latter). I'd like to match against both possibilities.

**Comment by RazrFalcon** [comment]
>However this is also what most Windows application choose fonts by

Yes, but this is not the only way. `fontdb` works with font family name (id1). Basically, to get the output you see on your screenshot, you have to generate it manually on your side and then deconstruct it for `frondb`. Because `Cascadia Mono Light` is not a `family-name`, `Cascadia Mono` is. And you can match it just fine with `fontdb`.

The problem is that font's creator can set font family to any value. So for example, `NotoSansDevanagari-CondensedMedium.ttf` contains:

|||
|---|---|
|Family|Noto Sans Devanagari Cn Md|
|Subfamily|Regular|
|Typographic Family|Noto Sans Devanagari|
|Typographic Subfamily|Condensed Medium|
|PostScript|NotoSansDevanagari-CondensedMedium|

Which one do you need and in what combination?

PS: ideally, we should use `Typographic Family`, but it's often missing and/or contains unexpected data.

**Comment by CryZe** [comment]
Basically I'm getting my font names from more or less basically the same list as Paint. Which seems to always be (after having looked at it a lot more now) "typographic family" (or just family, not sure, shouldn't be too hard to figure out) + "variation instance name", so I'd need to somehow take this string and find the correct font to load for it. I'm guessing it might make sense if I just pop off pieces at the end of the font until I hit a font family that exists and then look for a named variation instance with the rest? (+ maybe a PR to ttf-parser to query for the named variation instances)

**Comment by RazrFalcon** [comment]
Yes, I think this should be handled by the caller. Nothing we can do on the `fontdb` side.

>maybe a PR to ttf-parser to query for the named variation instances

You mean [STAT](https://docs.microsoft.com/en-us/typography/opentype/spec/stat)?

**Comment by CryZe** [comment]
fvar: https://docs.microsoft.com/en-us/typography/opentype/spec/fvar

There's a named instance array at the end

**Comment by RazrFalcon** [comment]
Oh right, they store the same value.

**Comment by RazrFalcon** [comment]
Seems like this is agains the CSS spec, so we would not support it either. A `fontdb::Family` is strictly a *Font Family* (ID 1).

**Comment by CryZe** [comment]
Mmh sounds like the spec needs to be updated to reflect reality then. I wonder how easy it is to get that change in.

**Comment by RazrFalcon** [comment]
By the CSS, you're suppose to use `font-weight` and `font-style` instead. CSS doesn't care about full typographic family names.

I'm not sure about origin of family names, but this is definitely a huge mess. There are so many ways to define and combine them that this is not even a joke.

**Comment by CryZe** [comment]
Wait, are you even sure that this "is against the CSS spec"? 

> Note: The precise way a set of fonts are grouped into font families varies depending upon the platform font management APIs. 

> On various platforms, different names are used to search for a font. For example, with the Windows GDI CreateIndirectFont API, either a family or fullname can be used to lookup a face, while on Mac OS X the CTFontCreateWithName API call is used to lookup a given face using the fullname and Postscript name. Under Linux, the fontconfig API allows fonts to be searched using any of these names. In situations where platform API’s automatically substitute other font choices, it may be necessary to verify a returned font matches a given name.

So not only does the spec seem to mention that full names and co. are usually used for the family names, but also all the OS APIs and browsers do it that way. So only supporting ID 1 isn't going to be a great user experience even if it was in the spec like that, which apparently it isn't even? (Or maybe I'm missing something)

Anyways, I'm not sure to what degree I'm still even affected by this issue, so I'm fine if it's closed.

**Comment by RazrFalcon** [comment]
I did some tests on macos and Chrome and Firefox ignored family names with `Regular`, `Bold`, `Light` suffixes. Safari didn't mind. This is the web inconsistency for you.

There are actually two issues here. First, I'm not sure if this is allowed by the spec to begin with. It's not really clear. And second, getting/generating those names are far from trivial and error-prone.

Here are my results for:

```xml
<text id="text1" x="32" y="100" font-family="Arial Bold" font-size="64">Text</text>
<text id="text2" x="32" y="150" font-family="Arial" font-weight="bold" font-size="64">Text</text>
```

![light-font](https://user-images.githubusercontent.com/725494/209476145-3b99073a-40ce-4585-8e1c-70e65d15f168.png)

As you can see, only Safari is able to detect both. And since `fondb` is web-first library, I must obey the Chrome.

**Comment by CryZe** [comment]
That's... surprising. I'll look into it more later. Also Merry Christmas :)

**Comment by RazrFalcon** [comment]
Thanks! 😃 You too.

**Comment by CryZe** [comment]
Not sure if this is necessarily the original problem, but it seems like the problem is rather opposite in that Arial Black, Calibri Light and co. are not considered to be part of Arial, Calibri and co. respectively.

![https://i.imgur.com/yTyPYBv.png](https://i.imgur.com/yTyPYBv.png)

I also tried it with cosmic-text and it absolutely runs into this problem and can't handle these fonts.

**Comment by RazrFalcon** [comment]
Strange. I will check Windows later, but macos fonts do not include Typographic Family. But they do have Full Name sometimes. 
This is one giant mess.

**Comment by RazrFalcon** [comment]
Just compare [MS](https://learn.microsoft.com/en-us/typography/opentype/spec/name#name-ids) docs about Typographic Family ID 16 and [Apple one](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html).

MS:

>16: Typographic Family name: The typographic family grouping doesn’t impose any constraints on the number of faces within it, in contrast with the 4-style family grouping (ID 1), which is present both for historical reasons and to express style linking groups. If name ID 16 is absent, then name ID 1 is considered to be the typographic family name. (In earlier versions of the specification, name ID 16 was known as “Preferred Family”.)

Apple:

>16: Preferred Family. In Windows, the Family name is displayed in the font menu, and the Subfamily name is presented as the Style name. For historical reasons, font families have contained a maximum of four styles, but font designers may group more than four fonts to a single family. The Preferred Family and Preferred Subfamily IDs allow font designers to include the preferred family/subfamily groupings. These IDs are only present if they are different from IDs 1 and 2.

Not only Apple calls it differently, but also Apple's name makes more sense. If it's preferred, then we should _prefer_ it.
The issue is that it will not fix your issue anyway, because it's still not a Full Name.

**Comment by RazrFalcon** [comment]
Yet another example: /System/Library/Fonts/MuktaMahee.ttc

- Family: MuktaMahee Regular
- Full Name: MuktaMahee Regular
- Typographic Family: Mukta Mahee

FontBook shows it as Mukta Mahee. So #35

**Comment by CryZe** [comment]
> The issue is that it will not fix your issue anyway, because it's still not a Full Name.

As shown here, I don't think Full Name is used by Chrome anymore and it's these three instead:
![image](https://user-images.githubusercontent.com/1451630/209518372-0cebe308-a69e-4a47-9a78-ff68b02343dd.jpeg)

I'm fine with only the first and third being supported I think.

**Comment by RazrFalcon** [comment]
Family + Subfamily = Full Name. Not sure if chrome generates one automatically or gets one from the file. Will have to dive into its source code to find out.

Using Typographic Name as preferred is an easy fix, but I'm not sure it will improve the situation much. Unless the Windows Calibri font has "Calibri Light" Typographic Name.
